# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/Owen/Documents/GitHub/CompArch/assignment_2/.Xil/Vivado-8660-OwenPC/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7k70tfbg484-2

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_vhdl -lib xil_defaultlib {
      C:/Users/Owen/Documents/GitHub/CompArch/assignment_2/assignment_2.srcs/sources_1/imports/new/ALU.vhd
      C:/Users/Owen/Documents/GitHub/CompArch/assignment_2/assignment_2.srcs/sources_1/imports/new/ArithmeticUnit16bit.vhd
      {C:/Users/Owen/Documents/GitHub/CompArch/assignment_2/assignment_2.srcs/sources_1/imports/new/B input Logic.vhd}
      C:/Users/Owen/Documents/GitHub/CompArch/assignment_3/assignment_3.srcs/sources_1/new/CAR.vhd
      C:/Users/Owen/Documents/GitHub/CompArch/assignment_3/assignment_3.srcs/sources_1/new/ControlMem.vhd
      C:/Users/Owen/Documents/GitHub/CompArch/assignment_2/assignment_2.srcs/sources_1/imports/new/FullAdder.vhd
      C:/Users/Owen/Documents/GitHub/CompArch/assignment_3/assignment_3.srcs/sources_1/new/InstructionRegister.vhd
      C:/Users/Owen/Documents/GitHub/CompArch/assignment_2/assignment_2.srcs/sources_1/imports/new/LogicUnit16bit.vhd
      C:/Users/Owen/Documents/GitHub/CompArch/assignment_2/assignment_2.srcs/sources_1/imports/new/LogicUnitSlice.vhd
      C:/Users/Owen/Documents/GitHub/CompArch/assignment_3/assignment_3.srcs/sources_1/new/Memory.vhd
      C:/Users/Owen/Documents/GitHub/CompArch/assignment_3/assignment_3.srcs/sources_1/new/ProgramCounter.vhd
      C:/Users/Owen/Documents/GitHub/CompArch/assignment_2/assignment_2.srcs/sources_1/imports/new/RippleCarryAdder.vhd
      C:/Users/Owen/Documents/GitHub/CompArch/assignment_2/assignment_2.srcs/sources_1/imports/new/Shifter.vhd
      C:/Users/Owen/Documents/GitHub/CompArch/assignment_2/assignment_2.srcs/sources_1/imports/new/ZeroDetect.vhd
      C:/Users/Owen/Documents/GitHub/CompArch/assignment_3/assignment_3.srcs/sources_1/new/datapath.vhd
      C:/Users/Owen/Documents/GitHub/CompArch/assignment_3/assignment_3.srcs/sources_1/new/decoder4to9.vhd
      C:/Users/Owen/Documents/GitHub/CompArch/assignment_2/assignment_2.srcs/sources_1/imports/new/function_Unit.vhd
      C:/Users/Owen/Documents/GitHub/CompArch/assignment_2/assignment_2.srcs/sources_1/imports/new/mux2.vhd
      C:/Users/Owen/Documents/GitHub/CompArch/assignment_3/assignment_3.srcs/sources_1/new/mux2_8bit.vhd
      C:/Users/Owen/Documents/GitHub/CompArch/assignment_2/assignment_2.srcs/sources_1/new/mux4_1bit.vhd
      C:/Users/Owen/Documents/GitHub/CompArch/assignment_3/assignment_3.srcs/sources_1/new/mux8_1bit.vhd
      C:/Users/Owen/Documents/GitHub/CompArch/assignment_3/assignment_3.srcs/sources_1/new/mux9.vhd
      C:/Users/Owen/Documents/GitHub/CompArch/assignment_2/assignment_2.srcs/sources_1/imports/new/reg16.vhd
      C:/Users/Owen/Documents/GitHub/CompArch/assignment_2/assignment_2.srcs/sources_1/imports/new/regfile.vhd
      C:/Users/Owen/Documents/GitHub/CompArch/assignment_3/assignment_3.srcs/sources_1/new/Microprocessor.vhd
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top Microprocessor
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "C:/Users/Owen/Documents/GitHub/CompArch/assignment_2/.Xil/Vivado-8660-OwenPC/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
